# Generated by Django 5.2 on 2025-04-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_name', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=100)),
                ('can_access', models.BooleanField(default=False)),
            ],
        ),
    ]
